version: 0.2

phases:
  install:
    commands:
      - echo Installing maven...
      - yum install -y maven
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Generating artifacts...
      - mvn clean package -Pproduction
  post_build:
    commands:
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'